# Generated by Django 4.2.1 on 2023-06-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
