# Generated by Django 4.2.1 on 2023-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets', '0003_alter_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='fotos/pets/<django.db.models.fields.CharField>'),
        ),
    ]
