# Generated by Django 4.2.1 on 2023-06-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopets', '0004_abrigo_alter_tutor_email_alter_tutor_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
    ]
