# Generated by Django 4.2.1 on 2023-06-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopets', '0006_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='estado',
            field=models.CharField(default='MS', max_length=2),
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopets.pet')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopets.tutor')),
            ],
        ),
    ]
